// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Product.Persistence.Context;

#nullable disable

namespace Modules.Product.Persistence.Migrations
{
    [DbContext(typeof(ProductWriteDbContext))]
    [Migration("20260615183513_Add-FeaturesValues")]
    partial class AddFeaturesValues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Modules.Product.Domain.Entities.Brands.Brand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Icon")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Image")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("UrlName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Title");

                    b.HasIndex("UrlName")
                        .IsUnique();

                    b.ToTable("ProductBrands", (string)null);
                });

            modelBuilder.Entity("Modules.Product.Domain.Entities.Categories.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Icon")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Image")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("UrlName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Title");

                    b.HasIndex("UrlName")
                        .IsUnique();

                    b.ToTable("ProductCategories", (string)null);
                });

            modelBuilder.Entity("Modules.Product.Domain.Entities.Colors.Color", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ProductColors", (string)null);
                });

            modelBuilder.Entity("Modules.Product.Domain.Entities.Discounts.ProductDiscount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaxUsageCount")
                        .HasColumnType("int");

                    b.Property<int>("Percentage")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("UsedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("ProductDiscounts", (string)null);
                });

            modelBuilder.Entity("Modules.Product.Domain.Entities.Features.FeaturesValues", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("FeatureValue")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<long?>("ProductFeaturesCategoryId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProductFeaturesId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ProductFeaturesCategoryId");

                    b.HasIndex("ProductFeaturesId");

                    b.ToTable("FeaturesValues", (string)null);
                });

            modelBuilder.Entity("Modules.Product.Domain.Entities.Features.ProductFeatures", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductFeatures");
                });

            modelBuilder.Entity("Modules.Product.Domain.Entities.FeaturesCategories.FeaturesCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("Title");

                    b.ToTable("ProductFeaturesCategories", (string)null);
                });

            modelBuilder.Entity("Modules.Product.Domain.Entities.Products.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("SellCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Modules.Product.Domain.Entities.Products.ProductComment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("StrongPoint")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("WeakPoint")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductComments", (string)null);
                });

            modelBuilder.Entity("Modules.Product.Domain.Entities.Products.ProductDiscountUse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<long>("ProductDiscountId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProductDiscountId1")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ProductDiscountId");

                    b.HasIndex("ProductDiscountId1");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductDiscountUses", (string)null);
                });

            modelBuilder.Entity("Modules.Product.Domain.Entities.Products.ProductGallery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("DisplayPriority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "DisplayPriority");

                    b.ToTable("ProductGalleries", (string)null);
                });

            modelBuilder.Entity("Modules.Product.Domain.Entities.Products.ProductSelectedBrands", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<long>("ProductBrandId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ProductBrandId");

                    b.HasIndex("ProductId", "ProductBrandId")
                        .IsUnique();

                    b.ToTable("ProductSelectedBrands", (string)null);
                });

            modelBuilder.Entity("Modules.Product.Domain.Entities.Products.ProductSelectedCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<long>("ProductCategoryId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("ProductId", "ProductCategoryId")
                        .IsUnique();

                    b.ToTable("ProductSelectedCategories", (string)null);
                });

            modelBuilder.Entity("Modules.Product.Domain.Entities.Products.ProductSelectedColors", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<long>("ProductColorId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ProductColorId");

                    b.HasIndex("ProductId", "ProductColorId")
                        .IsUnique();

                    b.ToTable("ProductSelectedColors", (string)null);
                });

            modelBuilder.Entity("Modules.Product.Domain.Entities.Products.ProductSelectedFeatures", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("FeatureValue")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<long?>("ProductFeaturesCategoryId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProductFeaturesId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ProductFeaturesCategoryId");

                    b.HasIndex("ProductFeaturesId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductSelectedFeatures", (string)null);
                });

            modelBuilder.Entity("Modules.Product.Domain.Entities.Brands.Brand", b =>
                {
                    b.HasOne("Modules.Product.Domain.Entities.Brands.Brand", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Modules.Product.Domain.Entities.Categories.Category", b =>
                {
                    b.HasOne("Modules.Product.Domain.Entities.Categories.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Modules.Product.Domain.Entities.Features.FeaturesValues", b =>
                {
                    b.HasOne("Modules.Product.Domain.Entities.FeaturesCategories.FeaturesCategory", "ProductFeaturesCategory")
                        .WithMany("FeaturesValues")
                        .HasForeignKey("ProductFeaturesCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Modules.Product.Domain.Entities.Features.ProductFeatures", "ProductFeatures")
                        .WithMany("FeaturesValues")
                        .HasForeignKey("ProductFeaturesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ProductFeatures");

                    b.Navigation("ProductFeaturesCategory");
                });

            modelBuilder.Entity("Modules.Product.Domain.Entities.Products.ProductComment", b =>
                {
                    b.HasOne("Modules.Product.Domain.Entities.Products.Product", "Product")
                        .WithMany("ProductComments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Modules.Product.Domain.Entities.Products.ProductDiscountUse", b =>
                {
                    b.HasOne("Modules.Product.Domain.Entities.Discounts.ProductDiscount", "ProductDiscount")
                        .WithMany()
                        .HasForeignKey("ProductDiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modules.Product.Domain.Entities.Discounts.ProductDiscount", null)
                        .WithMany("ProductDiscountUses")
                        .HasForeignKey("ProductDiscountId1");

                    b.HasOne("Modules.Product.Domain.Entities.Products.Product", "Product")
                        .WithMany("ProductDiscounts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductDiscount");
                });

            modelBuilder.Entity("Modules.Product.Domain.Entities.Products.ProductGallery", b =>
                {
                    b.HasOne("Modules.Product.Domain.Entities.Products.Product", "Product")
                        .WithMany("ProductGalleries")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Modules.Product.Domain.Entities.Products.ProductSelectedBrands", b =>
                {
                    b.HasOne("Modules.Product.Domain.Entities.Brands.Brand", "ProductBrand")
                        .WithMany("ProductSelectedBrands")
                        .HasForeignKey("ProductBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modules.Product.Domain.Entities.Products.Product", "Product")
                        .WithMany("ProductSelectedBrands")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductBrand");
                });

            modelBuilder.Entity("Modules.Product.Domain.Entities.Products.ProductSelectedCategory", b =>
                {
                    b.HasOne("Modules.Product.Domain.Entities.Categories.Category", "ProductCategory")
                        .WithMany("ProductSelectedCategories")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modules.Product.Domain.Entities.Products.Product", "Product")
                        .WithMany("ProductSelectedCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("Modules.Product.Domain.Entities.Products.ProductSelectedColors", b =>
                {
                    b.HasOne("Modules.Product.Domain.Entities.Colors.Color", "ProductColor")
                        .WithMany("ProductSelectedColors")
                        .HasForeignKey("ProductColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modules.Product.Domain.Entities.Products.Product", "Product")
                        .WithMany("ProductSelectedColors")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductColor");
                });

            modelBuilder.Entity("Modules.Product.Domain.Entities.Products.ProductSelectedFeatures", b =>
                {
                    b.HasOne("Modules.Product.Domain.Entities.FeaturesCategories.FeaturesCategory", "ProductFeaturesCategory")
                        .WithMany("ProductFeatures")
                        .HasForeignKey("ProductFeaturesCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Modules.Product.Domain.Entities.Features.ProductFeatures", "ProductFeatures")
                        .WithMany("ProductSelectedFeatures")
                        .HasForeignKey("ProductFeaturesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Modules.Product.Domain.Entities.Products.Product", "Product")
                        .WithMany("ProductFeatures")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductFeatures");

                    b.Navigation("ProductFeaturesCategory");
                });

            modelBuilder.Entity("Modules.Product.Domain.Entities.Brands.Brand", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("ProductSelectedBrands");
                });

            modelBuilder.Entity("Modules.Product.Domain.Entities.Categories.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("ProductSelectedCategories");
                });

            modelBuilder.Entity("Modules.Product.Domain.Entities.Colors.Color", b =>
                {
                    b.Navigation("ProductSelectedColors");
                });

            modelBuilder.Entity("Modules.Product.Domain.Entities.Discounts.ProductDiscount", b =>
                {
                    b.Navigation("ProductDiscountUses");
                });

            modelBuilder.Entity("Modules.Product.Domain.Entities.Features.ProductFeatures", b =>
                {
                    b.Navigation("FeaturesValues");

                    b.Navigation("ProductSelectedFeatures");
                });

            modelBuilder.Entity("Modules.Product.Domain.Entities.FeaturesCategories.FeaturesCategory", b =>
                {
                    b.Navigation("FeaturesValues");

                    b.Navigation("ProductFeatures");
                });

            modelBuilder.Entity("Modules.Product.Domain.Entities.Products.Product", b =>
                {
                    b.Navigation("ProductComments");

                    b.Navigation("ProductDiscounts");

                    b.Navigation("ProductFeatures");

                    b.Navigation("ProductGalleries");

                    b.Navigation("ProductSelectedBrands");

                    b.Navigation("ProductSelectedCategories");

                    b.Navigation("ProductSelectedColors");
                });
#pragma warning restore 612, 618
        }
    }
}
