<Project Sdk="Microsoft.NET.Sdk">

  

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Http" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.Extensions.Options" />
	  <PackageReference Include="Ardalis.Result" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Contracts\" />
  </ItemGroup>

</Project>
