<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Modules.Banner.Domain\Modules.Banner.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Resources\Banners\BannerFieldNames.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>BannerFieldNames.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Resources\Banners\BannerFieldNames.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>BannerFieldNames.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>
