//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modules.Order.Application.Contract.Resources.Orders {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrderValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Modules.Order.Application.Contract.Resources.Orders.OrderValidationMessages", typeof(OrderValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصول با موفقیت به سبد خرید اضافه شد.
        /// </summary>
        public static string AddOrderItem {
            get {
                return ResourceManager.GetString("AddOrderItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در افزودن آیتم سفارش.
        /// </summary>
        public static string ErrorAddingOrderItem {
            get {
                return ResourceManager.GetString("ErrorAddingOrderItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ایجاد سفارش.
        /// </summary>
        public static string ErrorCreatingOrder {
            get {
                return ResourceManager.GetString("ErrorCreatingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ایجاد سبد خریداری.
        /// </summary>
        public static string ErrorCreatingShoppingCart {
            get {
                return ResourceManager.GetString("ErrorCreatingShoppingCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در پیوند دادن جلسه به کاربر.
        /// </summary>
        public static string ErrorLinkingSessionToUser {
            get {
                return ResourceManager.GetString("ErrorLinkingSessionToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در حذف آیتم سفارش.
        /// </summary>
        public static string ErrorRemovingOrderItem {
            get {
                return ResourceManager.GetString("ErrorRemovingOrderItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در بروز رسانی آیتم سفارش.
        /// </summary>
        public static string ErrorUpdatingOrderItem {
            get {
                return ResourceManager.GetString("ErrorUpdatingOrderItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در بروز رسانی وضعیت سفارش.
        /// </summary>
        public static string ErrorUpdatingOrderStatus {
            get {
                return ResourceManager.GetString("ErrorUpdatingOrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در بروز رسانی مجموع مبلغ سفارش.
        /// </summary>
        public static string ErrorUpdatingOrderTotalAmount {
            get {
                return ResourceManager.GetString("ErrorUpdatingOrderTotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در بروز رسانی شماره رهگیری.
        /// </summary>
        public static string ErrorUpdatingTrackingNumber {
            get {
                return ResourceManager.GetString("ErrorUpdatingTrackingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت سفارش نامعتبر است.
        /// </summary>
        public static string InvalidOrderStatus {
            get {
                return ResourceManager.GetString("InvalidOrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن باید به فرمت 09XXXXXXXXX باشد.
        /// </summary>
        public static string MobileNumberFormat {
            get {
                return ResourceManager.GetString("MobileNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیتم سفارش یافت نشد.
        /// </summary>
        public static string OrderItemNotFound {
            get {
                return ResourceManager.GetString("OrderItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارش یافت نشد.
        /// </summary>
        public static string OrderNotFound {
            get {
                return ResourceManager.GetString("OrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصول با موفقیت از سبد خرید حذف شد.
        /// </summary>
        public static string RemoveOrderItem {
            get {
                return ResourceManager.GetString("RemoveOrderItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سبد خریداری یافت شد.
        /// </summary>
        public static string ShoppingCartFound {
            get {
                return ResourceManager.GetString("ShoppingCartFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سبد خریداری یافت نشد.
        /// </summary>
        public static string ShoppingCartNotFound {
            get {
                return ResourceManager.GetString("ShoppingCartNotFound", resourceCulture);
            }
        }
    }
}
