<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
        <ProjectReference Include="..\..\..\BuildingBlocks\Framwork\Framwork.csproj" />
        <ProjectReference Include="..\Modules.Product.Domain\Modules.Product.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Mapster" />
	  <PackageReference Include="Scrutor" />
    <PackageReference Include="Mapster.DependencyInjection" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Products\Services\" />
    <Folder Include="Products\Validation\" />
  </ItemGroup>
</Project>
