using SharedKernel.Base;

namespace Modules.Order.Domain.Entities;

public sealed class OrderItem : BaseEntityIdentity
{
    private OrderItem() { }

    public long OrderId { get; private set; }
    public long ProductId { get; private set; }
    public decimal UnitPrice { get; private set; }
    public int Quantity { get; private set; }
    public decimal? DiscountValue { get; private set; }
    public decimal TotalPrice { get; private set; }
    public DateTime CreatedAt { get; private set; }

    // Navigation property
    public OrderEntity Order { get; private set; }

    private OrderItem(
        long id,
        long orderId,
        long productId,
        decimal unitPrice,
        int quantity,
        decimal? discountValue,
        DateTime createdAt
    )
    {
        Id = id;
        OrderId = orderId;
        ProductId = productId;
        UnitPrice = unitPrice;
        Quantity = quantity;
        DiscountValue = discountValue;
        CreatedAt = createdAt;
        CalculateTotalPrice();
    }

    public static OrderItem Create(long orderId, long productId, decimal unitPrice, int quantity, decimal? discountValue = null)
    {
        if (orderId <= 0)
            throw new ArgumentException("Order ID must be greater than zero", nameof(orderId));

        if (productId <= 0)
            throw new ArgumentException("Product ID must be greater than zero", nameof(productId));

        if (quantity <= 0)
            throw new ArgumentException("Quantity must be greater than zero", nameof(quantity));

        if (unitPrice <= 0)
            throw new ArgumentException("Unit price must be greater than zero", nameof(unitPrice));

        if (discountValue.HasValue && discountValue.Value < 0)
            throw new ArgumentException("Discount value cannot be negative", nameof(discountValue));

        return new OrderItem(
            0, // Id will be generated by database
            orderId,
            productId,
            unitPrice,
            quantity,
            discountValue,
            DateTime.UtcNow
        );
    }

    public void UpdateQuantity(decimal newQuantity)
    {
        if (newQuantity <= 0)
            throw new ArgumentException("Quantity must be greater than zero", nameof(newQuantity));

        Quantity = (int)newQuantity;
        CalculateTotalPrice();
    }

    private void CalculateTotalPrice()
    {
        var basePrice = UnitPrice * Quantity;
        TotalPrice = DiscountValue.HasValue ? basePrice - DiscountValue.Value : basePrice;
    }
}
