using Ardalis.Result;
using Modules.Order.Domain.Enums;
using SharedKernel.Base;
using System.Transactions;

namespace Modules.Order.Domain.Entities;

public sealed class OrderEntity : BaseEntityIdentity
{
    private OrderEntity() { }
    private readonly List<OrderTransaction> _transactions = new();
    public long ShoppingCartId { get; private set; }
    public decimal TotalAmount { get; private set; }
    public OrderStatus Status { get; private set; } = OrderStatus.PendingPayment;
    public decimal TaxAmount { get; private set; }
    public bool TermsAccepted { get; private set; }
    public string? ShippingAddress { get; private set; }
    public string? MobileNumber { get; private set; }
    public string? TrackingNumber { get; private set; }
    public DateTime CreatedAt { get; private set; }

    // Navigation properties
    public ShoppingCart ShoppingCart { get; private set; }
    public ICollection<OrderItem> OrderItems { get; set; } = [];
    public IReadOnlyCollection<OrderTransaction> Transactions => _transactions;

    private OrderEntity(
        long id,
        long shoppingCartId,
        decimal totalAmount,
        OrderStatus status,
        decimal taxAmount,
        bool termsAccepted,
        string? shippingAddress,
        string? mobileNumber,
        string? trackingNumber,
        DateTime createdAt
    )
    {
        Id = id;
        ShoppingCartId = shoppingCartId;
        TotalAmount = totalAmount;
        Status = status;
        TaxAmount = taxAmount;
        TermsAccepted = termsAccepted;
        ShippingAddress = shippingAddress;
        MobileNumber = mobileNumber;
        TrackingNumber = trackingNumber;
        CreatedAt = createdAt;
    }


    public OrderTransaction CreatePaymentTransaction()
    {
        if (Status == OrderStatus.Paid)
            throw new InvalidOperationException("Order is already paid.");

        var transaction = new OrderTransaction(Id, TotalAmount);

        _transactions.Add(transaction);

        return transaction;
    }

    public static Result<OrderEntity> Create(
        long shoppingCartId,
        string? shippingAddress = null,
        string? mobileNumber = null,
        string? trackingNumber = null
    )
    {
        if (shoppingCartId <= 0)
            return Result.Invalid(new ValidationError { Identifier = nameof(shoppingCartId), ErrorMessage = "Shopping cart ID must be greater than zero" });

        return Result.Success(new OrderEntity(
            0, // Id will be generated by database
            shoppingCartId,
            0,
            OrderStatus.PendingPayment,
            0,
            false,
            shippingAddress,
            mobileNumber,
            trackingNumber,
            DateTime.UtcNow
        ));
    }

    public Result UpdateTrackingNumber(string trackingNumber)
    {
        if (Status != OrderStatus.PendingPayment)
            return Result.Invalid(new ValidationError { Identifier = nameof(TrackingNumber), ErrorMessage = "Order must be in Pending status to update tracking number" });

        if (string.IsNullOrWhiteSpace(trackingNumber))
            return Result.Invalid(new ValidationError { Identifier = nameof(trackingNumber), ErrorMessage = "Tracking number cannot be empty" });

        TrackingNumber = trackingNumber;
        return Result.Success();
    }

    public Result UpdateStatus(OrderStatus newStatus)
    {
        if (newStatus == OrderStatus.PendingPayment && Status != OrderStatus.PendingPayment)
            return Result.Invalid(new ValidationError { Identifier = nameof(Status), ErrorMessage = "Cannot set status to Pending" });

        Status = newStatus;
        return Result.Success();
    }

    public Result AddOrderItem(OrderItem orderItem)
    {
        if (orderItem == null)
            return Result.Invalid(new ValidationError { Identifier = nameof(orderItem), ErrorMessage = "Order item cannot be null" });

        if (Status != OrderStatus.PendingPayment)
            return Result.Invalid(new ValidationError { Identifier = nameof(Status), ErrorMessage = "Order must be in Pending status to add items" });

        OrderItems.Add(orderItem);
        TotalAmount += orderItem.TotalPrice;
        return Result.Success();
    }

    public Result RemoveOrderItem(OrderItem orderItem)
    {
        if (orderItem == null)
            return Result.Invalid(new ValidationError { Identifier = nameof(orderItem), ErrorMessage = "Order item cannot be null" });

        if (Status != OrderStatus.PendingPayment)
            return Result.Invalid(new ValidationError { Identifier = nameof(Status), ErrorMessage = "Order must be in Pending status to remove items" });

        OrderItems.Remove(orderItem);
        TotalAmount -= orderItem.TotalPrice;
        return Result.Success();
    }

    public Result UpdateOrderItem(OrderItem orderItem, decimal newQuantity)
    {
        if (orderItem == null)
            return Result.Invalid(new ValidationError { Identifier = nameof(orderItem), ErrorMessage = "Order item cannot be null" });

        if (Status != OrderStatus.PendingPayment)
            return Result.Invalid(new ValidationError { Identifier = nameof(Status), ErrorMessage = "Order must be in Pending status to update items" });

        var oldPrice = orderItem.TotalPrice;
        var quantityResult = orderItem.UpdateQuantity(newQuantity);
        if (!quantityResult.IsSuccess)
            return quantityResult;

        TotalAmount = TotalAmount - oldPrice + orderItem.TotalPrice;
        return Result.Success();
    }
    public Result MarkPaid()
    {
        if (Status == OrderStatus.Paid)
            return Result.Success();

        if (Status != OrderStatus.PendingPayment)
        return    Result.Conflict("Only pending payment orders can be paid.");

        Status = OrderStatus.Paid;
        return Result.Success();
    }

    public void MarkPaymentFailed()
    {
        if (Status == OrderStatus.Paid)
            return;

        Status = OrderStatus.PendingPayment;
    }
    public Result UpdateTotalAmount(decimal newAmount)
    {
        if (newAmount < 0)
            return Result.Invalid(new ValidationError { Identifier = nameof(newAmount), ErrorMessage = "Total amount cannot be negative" });

        TotalAmount = newAmount;
        return Result.Success();
    }

    public Result ChangeCart(long shoppingCartId)
    {
        if (shoppingCartId <= 0)
            return Result.Invalid(new ValidationError
            {
                Identifier = nameof(shoppingCartId),
                ErrorMessage = "Shopping cart ID must be greater than zero"
            });

        if (Status != OrderStatus.PendingPayment)
            return Result.Invalid(new ValidationError
            {
                Identifier = nameof(Status),
                ErrorMessage = "Only pending orders can be moved"
            });

        ShoppingCartId = shoppingCartId;
        return Result.Success();
    }

}


