using Ardalis.Result;
using Modules.Order.Domain.Enums;
using SharedKernel.Base;

namespace Modules.Order.Domain.Entities;

public sealed class OrderEntity : BaseEntityIdentity
{
    private OrderEntity() { }

    public long ShoppingCartId { get; private set; }
    public decimal TotalAmount { get; private set; }
    public OrderStatus Status { get; private set; } = OrderStatus.Pending;
    public decimal TaxAmount { get; private set; }
    public bool TermsAccepted { get; private set; }
    public string? ShippingAddress { get; private set; }
    public string? MobileNumber { get; private set; }
    public string? TrackingNumber { get; private set; }
    public long DisplayId { get; set; }
    public DateTime CreatedAt { get; private set; }

    // Navigation properties
    public ShoppingCart ShoppingCart { get; private set; }
    public ICollection<OrderItem> OrderItems { get; set; } = [];

    private OrderEntity(
        long id,
        long shoppingCartId,
        decimal totalAmount,
        OrderStatus status,
        decimal taxAmount,
        bool termsAccepted,
        string? shippingAddress,
        string? mobileNumber,
        string? trackingNumber,
        DateTime createdAt
    )
    {
        Id = id;
        ShoppingCartId = shoppingCartId;
        TotalAmount = totalAmount;
        Status = status;
        TaxAmount = taxAmount;
        TermsAccepted = termsAccepted;
        ShippingAddress = shippingAddress;
        MobileNumber = mobileNumber;
        TrackingNumber = trackingNumber;
        CreatedAt = createdAt;
    }

    public static Result<OrderEntity> Create(
        long shoppingCartId,
        string? shippingAddress = null,
        string? mobileNumber = null,
        string? trackingNumber = null
    )
    {
        if (shoppingCartId <= 0)
            return Result.Invalid(new ValidationError { Identifier = nameof(shoppingCartId), ErrorMessage = "Shopping cart ID must be greater than zero" });

        return Result.Success(new OrderEntity(
            0, // Id will be generated by database
            shoppingCartId,
            0,
            OrderStatus.Pending,
            0,
            false,
            shippingAddress,
            mobileNumber,
            trackingNumber,
            DateTime.UtcNow
        ));
    }

    public Result UpdateTrackingNumber(string trackingNumber)
    {
        if (Status != OrderStatus.Pending)
            return Result.Invalid(new ValidationError { Identifier = nameof(TrackingNumber), ErrorMessage = "Order must be in Pending status to update tracking number" });

        if (string.IsNullOrWhiteSpace(trackingNumber))
            return Result.Invalid(new ValidationError { Identifier = nameof(trackingNumber), ErrorMessage = "Tracking number cannot be empty" });

        TrackingNumber = trackingNumber;
        return Result.Success();
    }

    public Result UpdateStatus(OrderStatus newStatus)
    {
        if (newStatus == OrderStatus.Pending && Status != OrderStatus.Pending)
            return Result.Invalid(new ValidationError { Identifier = nameof(Status), ErrorMessage = "Cannot set status to Pending" });

        Status = newStatus;
        return Result.Success();
    }

    public Result AddOrderItem(OrderItem orderItem)
    {
        if (orderItem == null)
            return Result.Invalid(new ValidationError { Identifier = nameof(orderItem), ErrorMessage = "Order item cannot be null" });

        if (Status != OrderStatus.Pending)
            return Result.Invalid(new ValidationError { Identifier = nameof(Status), ErrorMessage = "Order must be in Pending status to add items" });

        OrderItems.Add(orderItem);
        TotalAmount += orderItem.TotalPrice;
        return Result.Success();
    }

    public Result RemoveOrderItem(OrderItem orderItem)
    {
        if (orderItem == null)
            return Result.Invalid(new ValidationError { Identifier = nameof(orderItem), ErrorMessage = "Order item cannot be null" });

        if (Status != OrderStatus.Pending)
            return Result.Invalid(new ValidationError { Identifier = nameof(Status), ErrorMessage = "Order must be in Pending status to remove items" });

        OrderItems.Remove(orderItem);
        TotalAmount -= orderItem.TotalPrice;
        return Result.Success();
    }

    public Result UpdateOrderItem(OrderItem orderItem, decimal newQuantity)
    {
        if (orderItem == null)
            return Result.Invalid(new ValidationError { Identifier = nameof(orderItem), ErrorMessage = "Order item cannot be null" });

        if (Status != OrderStatus.Pending)
            return Result.Invalid(new ValidationError { Identifier = nameof(Status), ErrorMessage = "Order must be in Pending status to update items" });

        var oldPrice = orderItem.TotalPrice;
        var quantityResult = orderItem.UpdateQuantity(newQuantity);
        if (!quantityResult.IsSuccess)
            return quantityResult;

        TotalAmount = TotalAmount - oldPrice + orderItem.TotalPrice;
        return Result.Success();
    }

    public Result UpdateTotalAmount(decimal newAmount)
    {
        if (newAmount < 0)
            return Result.Invalid(new ValidationError { Identifier = nameof(newAmount), ErrorMessage = "Total amount cannot be negative" });

        TotalAmount = newAmount;
        return Result.Success();
    }
}
