using Ardalis.Result;
using SharedKernel.Base;

namespace Modules.Order.Domain.Entities;

public sealed class OrderItem : BaseEntityIdentity
{
    private OrderItem() { }

    public long OrderId { get; private set; }
    public long ProductId { get; private set; }
    public decimal UnitPrice { get; private set; }
    public int Quantity { get; private set; }
    public decimal? DiscountValue { get; private set; }
    public decimal TotalPrice { get; private set; }
    public DateTime CreatedAt { get; private set; }

    // Navigation property
    public OrderEntity Order { get; private set; }

    private OrderItem(
        long id,
        long orderId,
        long productId,
        decimal unitPrice,
        int quantity,
        decimal? discountValue,
        DateTime createdAt
    )
    {
        Id = id;
        OrderId = orderId;
        ProductId = productId;
        UnitPrice = unitPrice;
        Quantity = quantity;
        DiscountValue = discountValue;
        CreatedAt = createdAt;
        CalculateTotalPrice();
    }

    public static Result<OrderItem> Create(long orderId, long productId, decimal unitPrice, int quantity, decimal? discountValue = null)
    {
        if (orderId <= 0)
            return Result.Invalid(new ValidationError { Identifier = nameof(orderId), ErrorMessage = "Order ID must be greater than zero" });

        if (productId <= 0)
            return Result.Invalid(new ValidationError { Identifier = nameof(productId), ErrorMessage = "Product ID must be greater than zero" });

        if (quantity <= 0)
            return Result.Invalid(new ValidationError { Identifier = nameof(quantity), ErrorMessage = "Quantity must be greater than zero" });

        if (unitPrice <= 0)
            return Result.Invalid(new ValidationError { Identifier = nameof(unitPrice), ErrorMessage = "Unit price must be greater than zero" });

        if (discountValue.HasValue && discountValue.Value < 0)
            return Result.Invalid(new ValidationError { Identifier = nameof(discountValue), ErrorMessage = "Discount value cannot be negative" });

        return Result.Success(new OrderItem(
            0, // Id will be generated by database
            orderId,
            productId,
            unitPrice,
            quantity,
            discountValue,
            DateTime.UtcNow
        ));
    }

    public Result UpdateQuantity(decimal newQuantity)
    {
        if (newQuantity <= 0)
            return Result.Invalid(new ValidationError { Identifier = nameof(newQuantity), ErrorMessage = "Quantity must be greater than zero" });

        Quantity = (int)newQuantity;
        CalculateTotalPrice();
        return Result.Success();
    }

    private void CalculateTotalPrice()
    {
        var basePrice = UnitPrice * Quantity;
        TotalPrice = DiscountValue.HasValue ? basePrice - DiscountValue.Value : basePrice;
    }
}
