using Modules.Order.Domain.Enums;
using SharedKernel.Base;

namespace Modules.Order.Domain.Entities;

public sealed class OrderEntity : BaseEntityIdentity
{
    private OrderEntity() { }

    public long ShoppingCartId { get; private set; }
    public decimal TotalAmount { get; private set; }
    public OrderStatus Status { get; private set; } = OrderStatus.Pending;
    public decimal TaxAmount { get; private set; }
    public bool TermsAccepted { get; private set; }
    public string? ShippingAddress { get; private set; }
    public string? MobileNumber { get; private set; }
    public string? TrackingNumber { get; private set; }
    public long DisplayId { get; set; }
    public DateTime CreatedAt { get; private set; }

    // Navigation properties
    public ShoppingCart ShoppingCart { get; private set; }
    public ICollection<OrderItem> OrderItems { get; set; } = [];

    private OrderEntity(
        long id,
        long shoppingCartId,
        decimal totalAmount,
        OrderStatus status,
        decimal taxAmount,
        bool termsAccepted,
        string? shippingAddress,
        string? mobileNumber,
        string? trackingNumber,
        DateTime createdAt
    )
    {
        Id = id;
        ShoppingCartId = shoppingCartId;
        TotalAmount = totalAmount;
        Status = status;
        TaxAmount = taxAmount;
        TermsAccepted = termsAccepted;
        ShippingAddress = shippingAddress;
        MobileNumber = mobileNumber;
        TrackingNumber = trackingNumber;
        CreatedAt = createdAt;
    }

    public static OrderEntity Create(
        long shoppingCartId,
        string? shippingAddress = null,
        string? mobileNumber = null,
        string? trackingNumber = null
    )
    {
        if (shoppingCartId <= 0)
            throw new ArgumentException("Shopping cart ID must be greater than zero", nameof(shoppingCartId));

        return new OrderEntity(
            0, // Id will be generated by database
            shoppingCartId,
            0,
            OrderStatus.Pending,
            0,
            false,
            shippingAddress,
            mobileNumber,
            trackingNumber,
            DateTime.UtcNow
        );
    }

    public void UpdateTrackingNumber(string trackingNumber)
    {
        if (Status != OrderStatus.Pending)
            throw new InvalidOperationException("Order must be in Pending status to update tracking number");

        if (string.IsNullOrWhiteSpace(trackingNumber))
            throw new ArgumentException("Tracking number cannot be empty", nameof(trackingNumber));

        TrackingNumber = trackingNumber;
    }

    public void UpdateStatus(OrderStatus newStatus)
    {
        if (newStatus == OrderStatus.Pending && Status != OrderStatus.Pending)
            throw new InvalidOperationException("Cannot set status to Pending");

        Status = newStatus;
    }

    public void AddOrderItem(OrderItem orderItem)
    {
        if (orderItem == null)
            throw new ArgumentNullException(nameof(orderItem));

        if (Status != OrderStatus.Pending)
            throw new InvalidOperationException("Order must be in Pending status to add items");

        OrderItems.Add(orderItem);
        TotalAmount += orderItem.TotalPrice;
    }

    public void RemoveOrderItem(OrderItem orderItem)
    {
        if (orderItem == null)
            throw new ArgumentNullException(nameof(orderItem));

        if (Status != OrderStatus.Pending)
            throw new InvalidOperationException("Order must be in Pending status to remove items");

        OrderItems.Remove(orderItem);
        TotalAmount -= orderItem.TotalPrice;
    }

    public void UpdateOrderItem(OrderItem orderItem, decimal newQuantity)
    {
        if (orderItem == null)
            throw new ArgumentNullException(nameof(orderItem));

        if (Status != OrderStatus.Pending)
            throw new InvalidOperationException("Order must be in Pending status to update items");

        var oldPrice = orderItem.TotalPrice;
        orderItem.UpdateQuantity(newQuantity);
        TotalAmount = TotalAmount - oldPrice + orderItem.TotalPrice;
    }

    public void UpdateTotalAmount(decimal newAmount)
    {
        if (newAmount < 0)
            throw new ArgumentException("Total amount cannot be negative", nameof(newAmount));

        TotalAmount = newAmount;
    }
}
