using SharedKernel.Base;

namespace Modules.Order.Domain.Entities;

public sealed class ShoppingCart : BaseEntityIdentity
{
    private ShoppingCart() { }

    public long SessionId { get; private set; }
    public long? UserId { get; private set; }
    public DateTime CreatedAt { get; private set; }

    // Navigation properties
    public ICollection<OrderEntity> Orders { get; set; } = [];
    
    private ShoppingCart(
        long id,
        long sessionId,
        long? userId,
        DateTime createdAt
    )
    {
        Id = id;
        SessionId = sessionId;
        UserId = userId;
        CreatedAt = createdAt;
    }

    public static ShoppingCart Create(long sessionId, long? userId = null)
    {
        if (sessionId <= 0)
            throw new ArgumentException("Session ID must be greater than zero", nameof(sessionId));

        return new ShoppingCart(
            0, // Id will be generated by database
            sessionId,
            userId,
            DateTime.UtcNow
        );
    }

    public void LinkToUser(long userId)
    {
        if (userId <= 0)
            throw new ArgumentException("User ID must be greater than zero", nameof(userId));

        UserId = userId;
    }
}
